// CAS BACnet Stack network type
pub const NETWORK_TYPE_IP: u8 = 0;
pub const NETWORK_TYPE_MSTP: u8 = 1;


// General constants
pub const NETWORK_PORT_LOWEST_PROTOCOL_LAYER: u32 = 4194303;

// Object Types
pub const OBJECT_TYPE_ANALOG_INPUT: u16 = 0;
pub const OBJECT_TYPE_ANALOG_OUTPUT: u16 = 1;
pub const OBJECT_TYPE_ANALOG_VALUE: u16 = 2;
pub const OBJECT_TYPE_BINARY_INPUT: u16 = 3;
pub const OBJECT_TYPE_BINARY_OUTPUT: u16 = 4;
pub const OBJECT_TYPE_BINARY_VALUE: u16 = 5;
//pub const OBJECT_TYPE_CALENDAR: u16 = 6;
//pub const OBJECT_TYPE_COMMAND: u16 = 7;
pub const OBJECT_TYPE_DEVICE: u16 = 8;
//pub const OBJECT_TYPE_EVENT_ENROLLMENT: u16 = 9;
//pub const OBJECT_TYPE_FILE: u16 = 10;
//pub const OBJECT_TYPE_GROUP: u16 = 11;
//pub const OBJECT_TYPE_LOOP: u16 = 12;
pub const OBJECT_TYPE_MULTI_STATE_INPUT: u16 = 13;
pub const OBJECT_TYPE_MULTI_STATE_OUTPUT: u16 = 14;
//pub const OBJECT_TYPE_NOTIFICATION_CLASS: u16 = 15;
//pub const OBJECT_TYPE_PROGRAM: u16 = 16;
//pub const OBJECT_TYPE_SCHEDULE: u16 = 17;
//pub const OBJECT_TYPE_AVERAGING: u16 = 18;
pub const OBJECT_TYPE_MULTI_STATE_VALUE: u16 = 19;
pub const OBJECT_TYPE_TREND_LOG: u16 = 20;
//pub const OBJECT_TYPE_LIFE_SAFETY_POINT: u16 = 21;
//pub const OBJECT_TYPE_LIFE_SAFETY_ZONE: u16 = 22;
//pub const OBJECT_TYPE_ACCUMULATOR: u16 = 23;
//pub const OBJECT_TYPE_PULSE_CONVERTER: u16 = 24;
//pub const OBJECT_TYPE_EVENT_LOG: u16 = 25;
//pub const OBJECT_TYPE_GLOBAL_GROUP: u16 = 26;
pub const OBJECT_TYPE_TREND_LOG_MULTIPLE: u16 = 27;
//pub const OBJECT_TYPE_LOAD_CONTROL: u16 = 28;
//pub const OBJECT_TYPE_STRUCTURED_VIEW: u16 = 29;
//pub const OBJECT_TYPE_ACCESS_DOOR: u16 = 30;
//pub const OBJECT_TYPE_TIMER: u16 = 31;
//pub const OBJECT_TYPE_ACCESS_CREDENTIAL: u16 = 32;
//pub const OBJECT_TYPE_ACCESS_POINT: u16 = 33;
//pub const OBJECT_TYPE_ACCESS_RIGHTS: u16 = 34;
//pub const OBJECT_TYPE_ACCESS_USER: u16 = 35;
//pub const OBJECT_TYPE_ACCESS_ZONE: u16 = 36;
//pub const OBJECT_TYPE_CREDENTIAL_DATA_INPUT: u16 = 37;
//pub const OBJECT_TYPE_NETWORK_SECURITY: u16 = 38;
pub const OBJECT_TYPE_BITSTRING_VALUE: u16 = 39;
pub const OBJECT_TYPE_CHARACTERSTRING_VALUE: u16 = 40;
//pub const OBJECT_TYPE_DATEPATTERN_VALUE: u16 = 41;
pub const OBJECT_TYPE_DATE_VALUE: u16 = 42;
//pub const OBJECT_TYPE_DATETIMEPATTERN_VALUE: u16 = 43;
pub const OBJECT_TYPE_DATETIME_VALUE: u16 = 44;
pub const OBJECT_TYPE_INTEGER_VALUE: u16 = 45;
pub const OBJECT_TYPE_LARGE_ANALOG_VALUE: u16 = 46;
pub const OBJECT_TYPE_OCTETSTRING_VALUE: u16 = 47;
pub const OBJECT_TYPE_POSITIVE_INTEGER_VALUE: u16 = 48;
//pub const OBJECT_TYPE_TIMEPATTERN_VALUE: u16 = 49;
pub const OBJECT_TYPE_TIME_VALUE: u16 = 50;
//pub const OBJECT_TYPE_NOTIFICATION_FORWARDER: u16 = 51;
//pub const OBJECT_TYPE_ALERT_ENROLLMENT: u16 = 52;
//pub const OBJECT_TYPE_CHANNEL: u16 = 53;
//pub const OBJECT_TYPE_LIGHTING_OUTPUT: u16 = 54;
//pub const OBJECT_TYPE_BINARY_LIGHTING_OUTPUT: u16 = 55;
pub const OBJECT_TYPE_NETWORK_PORT: u16 = 56;
//pub const OBJECT_TYPE_ELEVATOR_GROUP: u16 = 57;
//pub const OBJECT_TYPE_ESCALATOR: u16 = 58;
//pub const OBJECT_TYPE_LIFT: u16 = 59;

// Property Identifiers
pub const PROPERTY_IDENTIFIER_ALL: u32 = 8;
pub const PROPERTY_IDENTIFIER_COV_INCURMENT: u32 = 22;
pub const PROPERTY_IDENTIFIER_DAY_LIGHT_SAVINGS_STATUS: u32 = 24;
pub const PROPERTY_IDENTIFIER_DESCRIPTION: u32 = 28;
pub const PROPERTY_IDENTIFIER_LOCAL_DATE: u32 = 56;
pub const PROPERTY_IDENTIFIER_LOCAL_TIME: u32 = 57;
pub const PROPERTY_IDENTIFIER_NUMBER_OF_STATES: u32 = 74;
pub const PROPERTY_IDENTIFIER_OBJECT_NAME: u32 = 77;	
pub const PROPERTY_IDENTIFIER_PRESENT_VALUE: u32 = 85;
pub const PROPERTY_IDENTIFIER_PRIORITY_ARRAY: u32 = 87;
pub const PROPERTY_IDENTIFIER_RELIABILITY: u32 = 103;
pub const PROPERTY_IDENTIFIER_STATE_TEXT: u32 = 110;
pub const PROPERTY_IDENTIFIER_STATUS_FLAGS: u32 = 111;
pub const PROPERTY_IDENTIFIER_SYSTEM_STATUS: u32 = 112;
pub const PROPERTY_IDENTIFIER_UTC_OFFSET: u32 = 119;
pub const PROPERTY_IDENTIFIER_BIT_TEXT: u32 = 343;
pub const PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION: u32 = 12;
pub const PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT: u32 = 104;

	
	

pub const PROPERTY_IDENTIFIER_MAX_PRES_VALUE: u32 = 65;
pub const PROPERTY_IDENTIFIER_MIN_PRES_VALUE: u32 = 69;

// Network Port Property Identifiers
pub const PROPERTY_IDENTIFIER_IP_ADDRESS: u32 = 400;
pub const PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY: u32 = 401;
pub const PROPERTY_IDENTIFIER_IP_DNS_SERVER: u32 = 406;
pub const PROPERTY_IDENTIFIER_IP_SUBNET_MASK: u32 = 411;
pub const PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT: u32 = 412;
pub const PROPERTY_IDENTIFIER_BBMD_ACCEPT_FD_REGISTRATIONS: u32 = 413;
pub const PROPERTY_IDENTIFIER_BBMD_BROADCAST_DISTRIBUTION_TABLE: u32 = 414;
pub const PROPERTY_IDENTIFIER_BBMD_FOREIGN_DEVICE_TABLE: u32 = 415;
pub const PROPERTY_IDENTIFIER_CHANGES_PENDING: u32 = 416;
pub const PROPERTY_IDENTIFIER_FD_BBMD_ADDRESS: u32 = 418;
pub const PROPERTY_IDENTIFIER_FD_SUBSCRIPTION_LIFETIME: u32 = 419;
pub const PROPERTY_IDENTIFIER_LINK_SPEED: u32 = 420;
pub const PROPERTY_IDENTIFIER_MAC_ADDRESS: u32 = 423;
	
// Services Supported
pub const SERVICE_SUBSCRIBE_COV: u8 = 5;
pub const SERVICE_CREATE_OBJECT: u8 = 10;
pub const SERVICE_DELETE_OBJECT: u8 = 11;
pub const SERVICE_READ_PROPERTY_MULTIPLE: u8 = 14;
pub const SERVICE_WRITE_PROPERTY: u8 = 15;
pub const SERVICE_WRITE_PROPERTY_MULTIPLE: u8 = 16;
pub const SERVICE_DEVICE_COMMUNICATION_CONTROL: u8 = 17;
pub const SERVICE_CONFIRMED_TEXT_MESSAGE: u8 = 19;
pub const SERVICE_REINITIALIZE_DEVICE: u8 = 20;
pub const SERVICE_I_AM: u8 = 26;
pub const SERVICE_I_HAVE: u8 = 27;
pub const SERVICE_UNCONFIRMED_TEXT_MESSAGE: u8 = 31;
pub const SERVICE_TIME_SYNCHRONIZATION: u8 = 32;
pub const SERVICE_READ_RANGE: u8 = 35;
pub const SERVICE_UTC_TIME_SYNCHRONIZATION: u8 = 36;
pub const SERVICE_SUBSCRIBE_COV_PROPERTY: u8 = 38;
	

// Error Codes
pub const ERROR_MISSING_REQUIRED_PARAMETER: u8 = 16;
pub const ERROR_NO_SPACE_TO_WRITE_PROPERTY: u8 = 20;
pub const ERROR_PASSWORD_FAILURE: u8 = 26;
pub const ERROR_VALUE_OUT_OF_RANGE: u8 = 37;
pub const ERROR_OPTIONAL_FUNCTIONALITY_NOT_SUPPORTED: u8 = 45;
pub const ERROR_INVALID_CONFIGURATION_DATA: u8 = 46;

// Network Port FdBBmdAddressHostType
pub const HOST_TYPE_NONE: u8 = 0;
pub const HOST_TYPE_IPADDRESS: u8 = 1;
pub const HOST_TYPE_NAME: u8 = 2;

// Network Port FdBbmdAddressOffset
pub const FD_BBMD_ADDRESS_HOST: u8 = 1;
pub const FD_BBMD_ADDRESS_PORT: u8 = 2;

// Network Type
pub const NETWORK_TYPE_BACNET_IP: u8 = 0;
pub const NETWORK_TYPE_IPV4: u8 = 5;

// Protocol Level
pub const PROTOCOL_LEVEL_BACNET_APPLICATION: u8 = 2;

// Priority Array
pub const MAX_BACNET_PRIORITY: u8 = 16;

// Trend Log Buffer Size
pub const MAX_TREND_LOG_MAX_BUFFER_SIZE: u32 = 100;

// Data types 
pub const DATA_TYPE_NULL: u32 = 0;
pub const DATA_TYPE_BOOLEAN: u32 = 1;
pub const DATA_TYPE_UNSIGNED_INTEGER: u32 = 2;
pub const DATA_TYPE_SIGNED_INTEGER: u32 = 3;
pub const DATA_TYPE_REAL: u32 = 4;
pub const DATA_TYPE_DOUBLE: u32 = 5;
pub const DATA_TYPE_OCTET_STRING: u32 = 6;
pub const DATA_TYPE_CHARACTER_STRING: u32 = 7;
pub const DATA_TYPE_BIT_STRING: u32 = 8;
pub const DATA_TYPE_ENUMERATED: u32 = 9;
pub const DATA_TYPE_DATE: u32 = 10;
pub const DATA_TYPE_TIME: u32 = 11;
pub const DATA_TYPE_BACNET_OBJECT_IDENTIFIER: u32 = 12;
pub const DATA_TYPE_DATETIME: u32 = 27;

// Reinitialized State
pub const REINITIALIZED_STATE_WARM_START: u8 = 1;
pub const REINITIALIZED_STATE_ACTIVATE_CHANGES: u8 = 7;

// Debug Message Type
pub const BACNET_DEBUG_LOG_TYPE_ERROR: u8 = 0;
pub const BACNET_DEBUG_LOG_TYPE_INFO: u8 = 1;